services:
  - type: web
    name: studentflow
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: StudentFlow
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://studentflow-rbog.onrender.com
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: RUN_MIGRATIONS_ON_START
        value: "true"
      - key: RUN_SEED_ON_START
        value: "false"
      - key: PERF_LOG_AUTH
        value: "true"
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_URL
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: StudentFlow
      - key: ANDROID_APP_CERT_SHA256
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

      # CORS / SPA
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: SESSION_DOMAIN
        sync: false
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax
